# Generated by Django 4.1.5 on 2023-02-18 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_image', models.FileField(upload_to='gallerydocs/')),
                ('rent_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Owner.rent')),
            ],
        ),
    ]
