# Generated by Django 4.1.5 on 2023-02-10 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0006_subadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officer_name', models.CharField(max_length=50)),
                ('officer_contact', models.CharField(max_length=50)),
                ('officer_email', models.EmailField(max_length=254, unique=True)),
                ('officer_gender', models.CharField(max_length=50)),
                ('officer_address', models.TextField(null=True)),
                ('officer_photo', models.FileField(upload_to='officerdocs/')),
                ('officer_proof', models.FileField(upload_to='officerdocs')),
                ('officer_pwd', models.CharField(max_length=50, unique=True)),
                ('officer_doj', models.DateField(auto_now=True)),
                ('officer_state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Admin.state')),
                ('subadmin_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Admin.subadmin')),
            ],
        ),
    ]
