# Generated by Django 4.1.5 on 2023-02-17 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_vsts',
            field=models.IntegerField(default=0),
        ),
    ]
