# Generated by Django 4.1.5 on 2023-02-17 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_subadmin'),
        ('guest', '0002_user_user_vsts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=50)),
                ('owner_contact', models.CharField(max_length=50)),
                ('owner_email', models.EmailField(max_length=254, unique=True)),
                ('owner_gender', models.CharField(max_length=50)),
                ('owner_address', models.TextField(null=True)),
                ('owner_zipcode', models.CharField(max_length=50)),
                ('owner_photo', models.FileField(upload_to='userdocs/')),
                ('owner_proof', models.FileField(upload_to='userdocs/')),
                ('owner_pwd', models.CharField(max_length=50, unique=True)),
                ('owner_doj', models.DateField(auto_now=True)),
                ('owner_vsts', models.IntegerField(default=0)),
                ('owner_place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Admin.place')),
            ],
        ),
    ]
