# Generated by Django 4.1.5 on 2023-02-24 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complaint_content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complaint_date',
            field=models.DateField(auto_now=True),
        ),
    ]
