# Generated by Django 4.1.5 on 2023-03-09 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='feedback_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
