# Generated by Django 4.1.7 on 2023-03-14 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0003_owner'),
        ('Owner', '0002_gallery'),
        ('User', '0004_feedback_feedback_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_fromdate', models.DateField()),
                ('booking_todate', models.DateField()),
                ('booking_date', models.DateField(auto_now=True)),
                ('booking_status', models.IntegerField(default=0)),
                ('payment_status', models.IntegerField(default=0)),
                ('rent_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Owner.rent')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='guest.user')),
            ],
        ),
    ]
